spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/bank_services
        username: postgres
        password: postgres
    jpa: 
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true

        hibernate:
            ddl-auto: update
